"use client";

import { Inter } from "next/font/google";
import { Authenticator } from "@aws-amplify/ui-react";
import "@aws-amplify/ui-react/styles.css";
import "./app.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* TOOD: Utilize dynamic metadata: https://nextjs.org/docs/app/building-your-application/optimizing/metadata */}
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </head>
      <body>
        <Authenticator>
          {children}
        </Authenticator>
      </body>
    </html>
  );
}
